// <auto-generated />
using System;
using KITTests.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KITTests.Migrations
{
    [DbContext(typeof(KITTestDataContext))]
    partial class KITTestDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            SqlServerModelBuilderExtensions.HasDatabaseMaxSize(modelBuilder, "32 GB");
            SqlServerModelBuilderExtensions.HasServiceTierSql(modelBuilder, "'Free'");

            modelBuilder.Entity("KITTests.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<bool>("Semester")
                        .HasColumnType("bit");

                    b.Property<string>("TeacherName")
                        .HasColumnType("ntext");

                    b.HasKey("Id");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("KITTests.Models.TestData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("ntext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("date");

                    b.Property<string>("FilePath")
                        .HasColumnType("ntext");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Uploader")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("TestData");
                });

            modelBuilder.Entity("KITTests.Models.TestData", b =>
                {
                    b.HasOne("KITTests.Models.Subject", "Subject")
                        .WithMany("TestData")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("KITTests.Models.Subject", b =>
                {
                    b.Navigation("TestData");
                });
#pragma warning restore 612, 618
        }
    }
}
